services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    restart: unless-stopped
    working_dir: /app
    ports:
      - "443:1443/tcp"
      - "443:1443/udp"
    volumes:
      - ./:/app/tmp
    entrypoint: |
      sh -c "
        apk add --no-cache curl openssl util-linux jq && 
        cp /app/tmp/xconfig.json /app/xconfig.json &&
        cp /app/tmp/init-xray-server.sh /app/init-xray-server.sh &&
        chmod +x /app/init-xray-server.sh &&
        /app/init-xray-server.sh &&
        xray run -c /app/xconfig.json
      "